/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sqlParse(query: string): string
export type ParserWrapper = Parser
export class Parser {
  constructor()
  parseSql(query: string): string
}
